"""
Generated by 'django-admin startproject' using Django 1.8.2.
"""

import os

CONF_DIR = os.path.dirname(os.path.abspath(__file__))
BASE_DIR = os.path.dirname(CONF_DIR)
CONF_DIR_NAME = os.path.relpath(CONF_DIR, BASE_DIR)
PROJECT_NAME = "ekuOJ"
PROJECT_TITLE = "ekuOJ"

OJ_DATA_DIR = os.path.realpath(os.path.join(BASE_DIR, "OJ_data"))

# Quick-start development settings - unsuitable for production
SECRET_KEY = "a9w*6qa8)-)og5l+w1u+sx#6zkav!@u^ev1*1=!$&jr=lh1b1_"
DEBUG = True
ALLOWED_HOSTS = ["*"]

LOGIN_URL = "/account/login/"
LOGOUT_URL = "/account/logout/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = LOGIN_REDIRECT_URL

# Application definition

INSTALLED_APPS = (
	"django.contrib.admin",
	"django.contrib.auth",
	"django.contrib.contenttypes",
	"django.contrib.sessions",
	"django.contrib.messages",
	"django.contrib.staticfiles",
	"account",
	"main",
)

MIDDLEWARE_CLASSES = (
	"django.contrib.sessions.middleware.SessionMiddleware",
	"django.middleware.common.CommonMiddleware",
	"django.middleware.csrf.CsrfViewMiddleware",
	"django.contrib.auth.middleware.AuthenticationMiddleware",
	"django.contrib.auth.middleware.SessionAuthenticationMiddleware",
	"django.contrib.messages.middleware.MessageMiddleware",
	"django.middleware.clickjacking.XFrameOptionsMiddleware",
	"django.middleware.security.SecurityMiddleware",
)

ROOT_URLCONF = CONF_DIR_NAME+".urls"

TEMPLATES = [
	{
		"BACKEND": "django.template.backends.django.DjangoTemplates",
		"DIRS": [os.path.join(BASE_DIR, "templates")],
		"APP_DIRS": True,
		"OPTIONS": {
			"context_processors": [
				"django.template.context_processors.debug",
				"django.template.context_processors.request",
				"django.contrib.auth.context_processors.auth",
				"django.contrib.messages.context_processors.messages",
				"account.context_processors.settings_processor",
			],
		},
	},
]

WSGI_APPLICATION = CONF_DIR_NAME+".wsgi.application"


# Database

DATABASES = {
	"default": {
		"ENGINE": "django.db.backends.sqlite3",
		"NAME": os.path.join(BASE_DIR, "sqlite3.db"),
	}
}


# Internationalization

LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Kolkata"
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
EXTSTATIC_DIR = os.path.join(BASE_DIR, "extstatic")
STATICFILES_DIRS = (os.path.join(BASE_DIR, "static"), EXTSTATIC_DIR)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Other settings

import json

DEFAULT_SOURCE_LIM = 50000
LANG_INFO_PATH = os.path.join(BASE_DIR, "OJL3", "lang_info.json")
LANG_INFO = json.load(open(LANG_INFO_PATH))

from django.contrib import admin
admin.site.site_header = PROJECT_TITLE
admin.site.site_title = PROJECT_TITLE + " admin"
